const reasons = [
    "You are kind.",
    "You are compassionate.",
    "You are caring.",
    "You are generous.",
    "You are smart.",
    "You are intellectual.",
    "You are confident.",
    "You are patient.",
    "You are understanding.",
    "You are wise.",
    "You are a kid, at heart.",
    "You are strong-minded.",
    "You are strong-willed.",
    "You are affectionate.",
    "You are brave.",
    "You are respected.",
    "You are sincere.",
    "You are reliable.",
    "You are dependable.",
    "You are creative.",

    "You make me happy.",
    "You keep me safe.",
    "You make me feel seen.",
    "You make me feel heard.",
    "You feel like home, away from home.",
    "You know my favourite foods.",
    "You know my favourite flower.",
    "You know my favourite colour.",
    "You know what to say - and exactly when to say it.",
    "You give me space and time, without actually leaving me alone.",
    "You have the most pure heart.",
    "You have the cleanest of intentions",

    "You motivate me to be a better person.",
    "You have always been by my side - even during tough times.",
    "You make me feel like the most beautiful girl, everyday - even when I cried over my acne and did not want to look at myself.",
    "You have helped me build confidence.",
    "You loved until I learned to love myself, again, too.",
    "You take care of me.",
    "You answer every text.",
    "You answer every call.",
    "You buy the food that I crave.",
    "You buy me my favourite flowers, on the days I feel a little down.",
    "You give me the best, warmest, hugs.",
    "You attacked me with the softest kisses - and I felt more loved each time.",
    "You wipe my tears away.",
    "You calm my anxieties.",
    "You make special trips, every single time I need you.",
    "You buy me things, just at the mention of them.",
    "You try to help whenever and wherever you can.",
    "You are always as present as you possibly can be.",
    "You are the reason I believe that good people exist.",
    "You give me hope that better days will come.",
    "You make me laugh, without even trying - I might just love you too much.",
    "You give me respect.",
    "You respect our relationship and the bond we formed.",
    "You show appreciation towards me.",
    "You make me feel like the most special person and loved person, on my birthday (Thank you, for taking over from Thatha and Priya akka - you have no idea how much it means to me).",

    "You are handsome.",
    "You have pretty, swirls of honey, looking eyes.",
    "You are tall (I love looking up into your eyes).",
    "You have a, beautiful, contagious smile.",
    "You keep yourself fit - and fiiine.",
    "You keep your hair looking healthy.",
    "You carry yourself out maturely.",
    "You always achieve your goals.",
    "You are able to bring your dreams and aspirations to life.",
    "You have full faith and belief in God - it is admirable",
    "Your love and care reminds me of my Thatha",

    "You are my love - you are my best friend.",

    "YOU make my life, a life worth living - a life full of hope."

];

export default reasons;
